apiVersion: v1
kind: Service
metadata:
  name: jspwiki
  namespace: jspwiki
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: jspwiki
spec:
  type: ClusterIP
  selector:
    app: jspwiki
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
