apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: db-migrate
          image: your-registry/backend-image:latest
          command: ["python", "manage.py", "migrate", "--noinput"]
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
      containers:
        - name: backend
          image: nizamra/nasat-backend:65692065824e09e53418266013c060184499f611
          env:
            - name: DB_HOST
              value: postgres
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: dockerhub-cred
