apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: nasat-staging
type: Opaque
stringData:
  POSTGRES_PASSWORD: "nasat"
  # TODO: Put Django SECRET_KEY here!
  SECRET_KEY: "django-insecure-nasat-poc-key"
