apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: worker
      imagePullSecrets:
        - name: dockerhub-cred
      initContainers:
        - name: migrate
          image: nizamra/nasat-backend:cdc44b3fdf9088c7ed6dad7f6c51e9070d2c23a4
          command: ["python", "manage.py", "migrate", "--noinput", "--fake-initial"]
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
      containers:
        - name: backend
          image: nizamra/nasat-backend:cdc44b3fdf9088c7ed6dad7f6c51e9070d2c23a4
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
          livenessProbe:
            httpGet:
              path: /admin/login/
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /admin/login/
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
