apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: dockerhub-cred
      initContainers:
        # # Wait for Postgres to be reachable
        # - name: wait-for-db
        #   image: postgres:16
        #   command:
        #     - sh
        #     - -c
        #     - |
        #       getent hosts postgres
        # # Run the migration
        # - name: db-migrate
        #   image: nizamra/nasat-backend:52dc55f9ace38fd0414d1e642ef546bf3bd681fe
        #   command: ["sh", "-c", "python manage.py migrate users && python manage.py migrate"]
        #   envFrom:
        #     - configMapRef:
        #         name: backend-config
        #     - secretRef:
        #         name: backend-secrets
      containers:
        - name: backend
          image: nizamra/nasat-backend:52dc55f9ace38fd0414d1e642ef546bf3bd681fe
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
          livenessProbe:
            httpGet:
              path: /admin/login/
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /admin/login/
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5