apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: nasat-staging
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  POSTGRES_DB: nasat
  POSTGRES_USER: nasat
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
