apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: backend-static-secret
  namespace: nasat
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  infisicalAuthRef:
    name: backend-auth
    namespace: nasat
  syncOptions:
    refreshInterval: 60s
  sources:
    - projectId: "8e2d2a7d-599a-4c63-b54b-f2ffe7664937"
      environmentSlug: prod
      secretPath: "/"
  targets:
    - name: backend-secrets
      namespace: nasat
      kind: Secret
      creationPolicy: Owner
