apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalAuth
metadata:
  name: backend-auth
  namespace: nasat-staging
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  infisicalConnectionRef:
    name: infisical-connection
    namespace: infisical
  method: kubernetes
  kubernetes:
    identityIdRef:
      name: backend-infisical-identity
      namespace: nasat-staging
      key: identityId
    serviceAccountRef:
      name: backend-infisical-reader
      namespace: nasat-staging
