apiVersion: v1
kind: Service
metadata:
  name: backend
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
