apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: gotify-static-secret
  namespace: gotify
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  infisicalAuthRef:
    name: gotify-auth
    namespace: gotify
  syncOptions:
    refreshInterval: 60s
  sources:
    - projectId: "0d064592-e182-4c08-9851-b9faf63230e8"
      environmentSlug: staging
      secretPath: "/"
  targets:
    - name: gotify-secrets
      namespace: gotify
      kind: Secret
      creationPolicy: Owner
