# Secret for Gotify credentials
# Change these in production
apiVersion: v1
kind: Secret
metadata:
  name: gotify-secrets
  namespace: gotify
type: Opaque
stringData:
  GOTIFY_DEFAULTUSER_NAME: "admin"
  GOTIFY_DEFAULTUSER_PASS: "J2T9UY9RrlkAp-sj"