apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-2-2
  namespace: monitoring
  labels:
    grafana_dashboard: "1"
data:
  12250_rev1traefik-2-2.json: |-
{{ .Files.Get "dashboards/12250_rev1traefik-2-2.json" | indent 4 }}
