apiVersion: v1
kind: ConfigMap
metadata:
  name: loki2-0-global-metrics
  namespace: monitoring
  labels:
    grafana_dashboard: "1"
data:
  13407_rev1loki2-0-global-metrics.json: |-
{{ .Files.Get "dashboards/13407_rev1loki2-0-global-metrics.json" | indent 4 }}
