apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-views-nodes
  namespace: monitoring
  labels:
    grafana_dashboard: "1"
data:
  15759_rev40kubernetes-views-nodes.json: |-
{{ .Files.Get "dashboards/15759_rev40kubernetes-views-nodes.json" | indent 4 }}
