apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-views-namespaces
  namespace: monitoring
  labels:
    grafana_dashboard: "1"
data:
  15758_rev46kubernetes-views-namespaces.json: |-
{{ .Files.Get "dashboards/15758_rev46kubernetes-views-namespaces.json" | indent 4 }}
