apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-views-global
  namespace: monitoring
  labels:
    grafana_dashboard: "1"
data:
  15757_rev43kubernetes-views-global.json: |-
{{ .Files.Get "dashboards/15757_rev43kubernetes-views-global.json" | indent 4 }}
