apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-system-api-server
  namespace: monitoring
  labels:
    grafana_dashboard: "1"
data:
  15761_rev21kubernetes-system-api-server.json: |-
{{ .Files.Get "dashboards/15761_rev21kubernetes-system-api-server.json" | indent 4 }}
