apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-cluster-summary
  namespace: monitoring
  labels:
    grafana_dashboard: "1"
data:
  8685_rev1k8s-cluster-summary.json: |-
{{ .Files.Get "dashboards/8685_rev1k8s-cluster-summary.json" | indent 4 }}
