apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc-longhorn
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-critical
  resources:
    requests:
      storage: 14Gi
