apiVersion: v1
kind: Service
metadata:
  name: freshrss
  namespace: freshrss
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: freshrss
spec:
  type: ClusterIP
  selector:
    app: freshrss
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
