apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-config
  namespace: paperless
data:
  PAPERLESS_URL: "http://paperless.nasat.local"
  PAPERLESS_ALLOWED_HOSTS: "paperless.nasat.local,localhost,127.0.0.1"
  PAPERLESS_CSRF_TRUSTED_ORIGINS: "http://paperless.nasat.local"

  PAPERLESS_DBENGINE: "postgresql"
  PAPERLESS_DBHOST: "postgres.paperless.svc.cluster.local"
  PAPERLESS_DBPORT: "5432"
  PAPERLESS_DBNAME: "paperless"
  PAPERLESS_DBUSER: "paperless"
  PAPERLESS_DBSSLMODE: "prefer"

  PAPERLESS_REDIS: "redis://redis.paperless.svc.cluster.local:6379"

  PAPERLESS_OCR_LANGUAGE: "eng"

  PAPERLESS_TIME_ZONE: "UTC"

  PAPERLESS_USE_X_FORWARD_HOST: "true"

  PAPERLESS_PORT: "8000"
  PAPERLESS_WEBSERVER_WORKERS: "1"

  USERMAP_UID: "1000"
  USERMAP_GID: "1000"
