apiVersion: v1
kind: Secret
metadata:
  name: paperless-secrets
  namespace: paperless
type: Opaque
stringData:
  PAPERLESS_SECRET_KEY: "wKNeF1fUMa9M4px9vlFCLHQ0lCaDE5aqP2XKvEDu9qjAAI5Loz3R1dfkS0Wq3M4u0TNXrVX1NNMsAyyrwqnRwQ=="
  PAPERLESS_ADMIN_USER: "admin"
  PAPERLESS_ADMIN_PASSWORD: "J2T9UY9RrlkAp-sj"
  PAPERLESS_ADMIN_MAIL: "admin@nasat.local"
  PAPERLESS_DBPASS: "J2T9UY9RrlkAp-sj"
  POSTGRES_PASSWORD: "J2T9UY9RrlkAp-sj"
