apiVersion: v1
kind: Secret
metadata:
  name: immich-secrets
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  DB_PASSWORD: "J2T9UY9RrlkAp-sj"
  JWT_SECRET: "J2T9UY9RrlkAp-sj"
  IMMACC_PASSWORD: "J2T9UY9RrlkAp-sj"
