apiVersion: v1
kind: Secret
metadata:
  name: longhorn-backup-target
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_SECRET_ACCESS_KEY: "J2T9UY9RrlkAp-sj"
  AWS_ENDPOINTS: "http://minio.default.svc.cluster.local:9000"
