kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      scrapeInterval: "20s"
      retention: "30d"
      retentionSize: "10GB"
      resources:
        requests:
          memory: "800Mi"
        limits:
          memory: "1.5Gi"
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: local-path
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
    rbac:
      pspEnabled: false

  grafana:
    persistence:
      enabled: true
      storageClassName: local-path
      size: 2Gi
    adminPassword: "adminadmin"
    rbac:
      pspEnabled: false
    ingress:
      enabled: true
      hosts:
        - grafana.nasat.local
      path: /
      pathType: Prefix

  # Disable Alerting
  alertmanager:
    enabled: false

  # Correctly disable webhooks for the Operator
  prometheusOperator:
    admissionWebhooks:
      enabled: false
      patch:
        enabled: false
    tls:
      enabled: false  # Explicitly disable TLS for the operator

  # Disable scraping for K3s internal components
  kubeProxy:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeControllerManager:
    enabled: false

  prometheus-node-exporter:
    rbac:
      pspEnabled: false
