apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-self.yaml
  - infisical-operator.yaml
  - infisical.yaml
  - longhorn.yaml
  - nasat-master.yaml
  - nasat-staging.yaml
  - playground.yaml
  - prometheus-stack.yaml
  # - loki-stack.yaml
