apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  sources:
    repoURL: https://github.com/nizamra/nasat
    targetRevision: staging
    path: infrastructure/longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - pruneLast=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
