apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  ignoreDifferences:
    - group: storage.k8s.io
      kind: StorageClass
      name: longhorn-critical
      jsonPointers:
        - /parameters
    - group: storage.k8s.io
      kind: StorageClass
      name: longhorn-standard
      jsonPointers:
        - /parameters
  sources:
    - repoURL: https://github.com/nizamra/nasat
      targetRevision: master
      path: infrastructure/longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - pruneLast=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
