apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data
  namespace: linkding
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: worker
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
