apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalAuth
metadata:
  name: immich-auth
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  infisicalConnectionRef:
    name: infisical-connection
    namespace: infisical
  method: kubernetes
  kubernetes:
    identityIdRef:
      name: immich-infisical-identity
      namespace: immich
      key: identityId
    serviceAccountRef:
      name: immich-infisical-reader
      namespace: immich
