apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: immich-static-secret
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  infisicalAuthRef:
    name: immich-auth
    namespace: immich
  syncOptions:
    refreshInterval: 60s
  sources:
    - projectId: "a2af403f-659f-4c3c-8872-2fd6b8b16125"
      environmentSlug: staging
      secretPath: "/"
  targets:
    - name: immich-secrets
      namespace: immich
      kind: Secret
      creationPolicy: Owner
