name: Build, Test, and Push All Nasat

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: true
        type: choice
        options:
          - master
          - staging

permissions:
  contents: write

jobs:
  call-frontend:
    uses: ./.github/workflows/build-docker-push-fr.yaml
    with:
      branch: ${{ inputs.branch }}
    secrets: inherit

  call-backend:
    uses: ./.github/workflows/build-docker-push-bk.yaml
    with:
      branch: ${{ inputs.branch }}
    secrets: inherit
